name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add HF remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://TatianaGol:${HF_TOKEN}@huggingface.co/spaces/TatianaGol/Multimodal_Assistant || true
          git remote set-url space https://TatianaGol:${HF_TOKEN}@huggingface.co/spaces/TatianaGol/Multimodal_Assistant

      - name: Force-push GitHub main to Space
        run: |
          git fetch origin main
          git checkout -B main origin/main
          git push space main --force
