name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          lfs: false

      - name: Setup Git
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add HF remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://TatianaGol:${HF_TOKEN}@huggingface.co/spaces/TatianaGol/Multimodal_Assistant || true
          git remote set-url space https://TatianaGol:${HF_TOKEN}@huggingface.co/spaces/TatianaGol/Multimodal_Assistant

      # >>> KLUCZOWY KROK – tworzymy gałąź bez historii (orphan)
      - name: Create orphan snapshot and push to Space main
        run: |
          git checkout --orphan space-deploy
          git rm -r --cached . >/dev/null 2>&1 || true
          git add -A
          git commit -m "Deploy snapshot from GitHub main (no history)"
          git push -f space HEAD:main
